# Generated by Django 5.0.6 on 2024-05-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('O', 'Other')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='boigraphy'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='proflie_images', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='website'),
        ),
    ]
