# Generated by Django 5.0.6 on 2024-05-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_followed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='followers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='following_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='posts_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
