# Generated by Django 5.0.6 on 2024-05-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_likes_post_likes_count_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
